//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Butchers.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Measurement
    {
        public int MeasurementId { get; set; }
        public string MeasurementName { get; set; }
        public Nullable<decimal> GramsPerMeasurement { get; set; }
    }
}
