//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Butchers.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderDetails
    {
        public int OrderDetailsId { get; set; }
        public int OrderNo { get; set; }
        public System.DateTime CollectFrom { get; set; }
        public System.DateTime CollectBy { get; set; }
        public bool Collected { get; set; }
    }
}
