//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Butchers.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int Id { get; set; }
        public System.DateTime OrderDate { get; set; }
        public Nullable<System.DateTime> CollectFrom { get; set; }
        public Nullable<System.DateTime> CollectBy { get; set; }
        public string Customer { get; set; }
        public bool Collected { get; set; }
        public string PromoCode { get; set; }
        public decimal TotalCost { get; set; }
    }
}
