//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Butchers.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockTransaction
    {
        public int TransactionId { get; set; }
        public int ProductItemId { get; set; }
        public string AddedBy { get; set; }
        public int CurrentStock { get; set; }
        public int QtyToAdd { get; set; }
        public System.DateTime DateAdded { get; set; }
    }
}
